name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

permissions:
  contents: write

defaults:
  run:
    working-directory: ./documentation-website

jobs:
  setup:
    name: 'Checkout, Setup Node, Install dependencies'
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: npm

        - name: Install dependencies
          run: npm ci

  build:
    needs: setup
    name: 'Build Documentation'
    runs-on: ubuntu-latest
    steps:
        - name: Build docusaurus
          run: npm run build


  deploy:
    needs: build
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output URL
        env:
          PAGE_URL: ${{ steps.deployment.outputs.page_url }}
        run: echo "Deployed to $PAGE_URL."
